# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-28 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cenovnik',
            fields=[
                ('id_cenovnika', models.IntegerField(db_column='ID_CENOVNIKA', primary_key=True, serialize=False)),
                ('datum_vazena', models.DateTimeField(blank=True, db_column='DATUM_VAZENA', null=True)),
            ],
            options={
                'db_table': 'cenovnik',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Faktura',
            fields=[
                ('id_fakture', models.IntegerField(db_column='ID_FAKTURE', primary_key=True, serialize=False)),
                ('broj_fakture', models.IntegerField(blank=True, db_column='BROJ_FAKTURE', null=True)),
                ('datum_fakture', models.DateTimeField(blank=True, db_column='DATUM_FAKTURE', null=True)),
                ('datum_valute', models.DateTimeField(blank=True, db_column='DATUM_VALUTE', null=True)),
                ('ukupan_rabat', models.DecimalField(blank=True, db_column='UKUPAN_RABAT', decimal_places=0, max_digits=10, null=True)),
                ('ukupan_iznos_bez_pdv_a', models.DecimalField(blank=True, db_column='UKUPAN_IZNOS_BEZ_PDV_A', decimal_places=0, max_digits=10, null=True)),
                ('ukupan_pdv', models.DecimalField(blank=True, db_column='UKUPAN_PDV', decimal_places=0, max_digits=10, null=True)),
                ('ukupno_za_placanje', models.DecimalField(blank=True, db_column='UKUPNO_ZA_PLACANJE', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'faktura',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GrupaProizvoda',
            fields=[
                ('id_grupe', models.IntegerField(db_column='ID_GRUPE', primary_key=True, serialize=False)),
                ('naziv_grupe', models.CharField(blank=True, db_column='NAZIV_GRUPE', max_length=100, null=True)),
            ],
            options={
                'db_table': 'grupa_proizvoda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JedinicaMere',
            fields=[
                ('id_jedinice', models.IntegerField(db_column='ID_JEDINICE', primary_key=True, serialize=False)),
                ('naziv_jedinice_mere', models.CharField(blank=True, db_column='NAZIV_JEDINICE_MERE', max_length=100, null=True)),
                ('skracenica', models.CharField(blank=True, db_column='SKRACENICA', max_length=10, null=True)),
            ],
            options={
                'db_table': 'jedinica_mere',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pdv',
            fields=[
                ('naziv_pdv_a', models.CharField(blank=True, db_column='NAZIV_PDV_A', max_length=50, null=True)),
                ('id_pdv_a', models.IntegerField(db_column='ID_PDV_A', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'pdv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoslovnaGodina',
            fields=[
                ('id_godine', models.IntegerField(db_column='ID_GODINE', primary_key=True, serialize=False)),
                ('godina', models.IntegerField(blank=True, db_column='GODINA', null=True)),
                ('zakljucena_field', models.IntegerField(blank=True, db_column='ZAKLJUCENA_', null=True)),
            ],
            options={
                'db_table': 'poslovna_godina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PoslovniPartner',
            fields=[
                ('vrsta', models.CharField(blank=True, db_column='VRSTA', max_length=50, null=True)),
                ('id_poslovnog_partnera', models.IntegerField(db_column='ID_POSLOVNOG_PARTNERA', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'poslovni_partner',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Preduzece',
            fields=[
                ('idpreduzeca', models.IntegerField(db_column='IDPREDUZECA', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'preduzece',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('vrsta_proizvoda', models.CharField(blank=True, db_column='VRSTA_PROIZVODA', max_length=50, null=True)),
                ('id_proizvoda', models.IntegerField(db_column='ID_PROIZVODA', primary_key=True, serialize=False)),
                ('naziv_proizvoda', models.CharField(blank=True, db_column='NAZIV_PROIZVODA', max_length=50, null=True)),
            ],
            options={
                'db_table': 'proizvod',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StavkeCenovnika',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idstavke', models.IntegerField(db_column='IDSTAVKE')),
                ('cena', models.DecimalField(blank=True, db_column='CENA', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stavke_cenovnika',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StavkeFakture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rbrstavke', models.IntegerField(db_column='RBRSTAVKE')),
                ('kolicina', models.DecimalField(blank=True, db_column='KOLICINA', decimal_places=0, max_digits=10, null=True)),
                ('rabat', models.DecimalField(blank=True, db_column='RABAT', decimal_places=0, max_digits=10, null=True)),
                ('jedinicna_cena', models.DecimalField(blank=True, db_column='JEDINICNA_CENA', decimal_places=0, max_digits=10, null=True)),
                ('stopa_pdv_a', models.DecimalField(blank=True, db_column='STOPA_PDV_A', decimal_places=0, max_digits=10, null=True)),
                ('osnovica', models.DecimalField(blank=True, db_column='OSNOVICA', decimal_places=0, max_digits=10, null=True)),
                ('iznos_pdv_a', models.DecimalField(blank=True, db_column='IZNOS_PDV_A', decimal_places=0, max_digits=10, null=True)),
                ('ukupan_iznos', models.DecimalField(blank=True, db_column='UKUPAN_IZNOS', decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'stavke_fakture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopaPdvA',
            fields=[
                ('id_stope', models.IntegerField(db_column='ID_STOPE', primary_key=True, serialize=False)),
                ('stopa', models.DecimalField(blank=True, db_column='STOPA', decimal_places=0, max_digits=10, null=True)),
                ('datum_vazenja', models.DateTimeField(blank=True, db_column='DATUM_VAZENJA', null=True)),
            ],
            options={
                'db_table': 'stopa_pdv_a',
                'managed': False,
            },
        ),
    ]
